# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
          
# HTTP Server
server:
  address: 127.0.0.1
  port: 4444   # HTTP (Tomcat) port
  
  
