# Spring properties
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost/test
      
# HTTP Server
server:
  address: 159.203.115.158
  port: 4444   # HTTP (Tomcat) port
  